const fs=require('node:fs')
const assert=require('node:assert/strict')

const read=p=>fs.readFileSync(p,'utf8')
const data=read('lib/data.js')
const playersPage=read('app/players/page.js')
const playersTable=read('components/PlayersTable.js')
const playerDetail=read('app/players/[id]/page.js')
const squads=read('app/squads/page.js')
const squad=read('app/squad/page.js')
const roles=read('app/roles/page.js')
const availability=read('app/availability/page.js')
const teamDetail=read('app/teams/[id]/page.js')
const pricing=read('app/pricing/page.js')
const home=read('app/page.js')
const css=read('components/PremiumViews.module.css')
const gate=read('components/AccessGate.js')

assert.match(data,/tier:'visitor'/)
assert.match(data,/tier:activePro \? 'pro' : 'member'/)
assert.match(playersPage,/accessTier=\{auth\.tier\}/)
assert.match(playersTable,/const isPro=accessTier==='pro'/)
assert.match(playersTable,/P25\/P90/)
assert.match(playersTable,/isPro\?<>{head\('p25'/)
assert.match(playerDetail,/getAuthState/)
assert.match(playerDetail,/GELİŞMİŞ • OYUNCU DERİNLİĞİ/)
assert.match(squads,/auth\.tier==='visitor'/)
assert.match(squads,/auth\.plan==='pro'\?await getRecommendation\('alternative'\):null/)
assert.match(squads,/GELİŞMİŞ • AGRESİF 11/)
assert.match(squad,/if\(!auth\.userId\)/)
assert.match(roles,/auth\.plan!=='pro'/)
assert.match(availability,/rows\.slice\(0,8\)/)
assert.match(teamDetail,/GELİŞMİŞ • TAKIM DERİNLİĞİ/)
assert.match(pricing,/ZİYARETÇİ/)
assert.match(pricing,/ÜCRETSİZ ÜYE/)
assert.match(pricing,/GELİŞMİŞ ÜYELİK/)
assert.match(home,/GELİŞMİŞ • Tavan analizi/)
assert.match(gate,/Ücretsiz hesap aç \/ giriş yap/)
assert.match(css,/Access tiers and Pro gates 2026-10-01/)

console.log('access tier contract ok')
