const fs=require('node:fs')
const assert=require('node:assert/strict')
const actions=fs.readFileSync('app/actions.js','utf8')
const publicClient=fs.readFileSync('lib/supabase/public.js','utf8')
const api=fs.readFileSync('app/api/scout-data/route.js','utf8')
const ci=fs.readFileSync('.github/workflows/ci.yml','utf8')
const migration=fs.readFileSync('supabase/migrations/20260927200000_squad_write_hardening.sql','utf8')
assert.match(actions,/ignoreDuplicates:true/)
assert.match(actions,/MAX_PLAYERS_PER_CLUB/)
assert.match(publicClient,/failFastPublicFetch/)
assert.match(api,/section==='summary'/)
assert.match(api,/private, no-store/)
assert.match(ci,/npm ci --no-audit --no-fund/)
assert.match(migration,/security definer/i)
assert.match(migration,/CLUB_LIMIT_EXCEEDED/)
assert.match(migration,/revoke insert,update,delete/i)
console.log('auditHardening: ok')
