const fs=require('node:fs')
const assert=require('node:assert/strict')
const actions=fs.readFileSync('app/actions.js','utf8')
const publicClient=fs.readFileSync('lib/supabase/public.js','utf8')
const api=fs.readFileSync('app/api/scout-data/route.js','utf8')
const ci=fs.readFileSync('.github/workflows/ci.yml','utf8')
const prepare=fs.readFileSync('supabase/migrations/20260927100422_prepare_squad_rpc_v2.sql','utf8')
const privacy=fs.readFileSync('supabase/migrations/20260927101100_post_deploy_restrict_sensitive_public_columns.sql','utf8')
const lockdown=fs.readFileSync('supabase/migrations/20260927101200_post_deploy_squad_write_lockdown.sql','utf8')
assert.match(actions,/ignoreDuplicates:true/)
assert.match(actions,/MAX_PLAYERS_PER_CLUB/)
assert.match(publicClient,/failFastPublicFetch/)
assert.match(api,/section==='summary'/)
assert.match(api,/private, no-store/)
assert.match(ci,/npm ci --no-audit --no-fund/)
assert.match(prepare,/private\.save_user_squad_impl/)
assert.match(prepare,/security definer/i)
assert.match(prepare,/set search_path = ''/)
assert.match(prepare,/CLUB_LIMIT_EXCEEDED/)
assert.doesNotMatch(prepare,/revoke insert,update,delete on public\.scout_user_squads/)
assert.match(privacy,/revoke select on table public\.scout_availability/)
assert.match(lockdown,/revoke insert,update,delete on public\.scout_user_squads/)
assert.match(lockdown,/revoke insert,update,delete on public\.scout_user_squad_members/)
console.log('auditHardening: ok')
