const fs=require('node:fs')
const assert=require('node:assert/strict')

const deploy=fs.readFileSync('.github/workflows/cloudflare-deploy.yml','utf8')
const smoke=fs.readFileSync('.github/workflows/post-deploy-smoke.yml','utf8')
const health=fs.readFileSync('app/api/health/route.js','utf8')
const wrangler=fs.readFileSync('wrangler.jsonc','utf8')

assert.match(deploy,/Cloudflare Workers deploy/)
assert.match(deploy,/npm run deploy/)
assert.match(deploy,/GITHUB_SHA/)
assert.match(deploy,/tff-fantezi\.ecetin1998\.workers\.dev/)
assert.match(smoke,/EXPECTED_SHA/)
assert.match(smoke,/workflow_run\.head_sha/)
assert.match(health,/NEXT_PUBLIC_BUILD_SHA/)
assert.match(health,/Cache-Control':'no-store/)
assert.match(wrangler,/"name": "tff-fantezi"/)
const smokeScript=fs.readFileSync('scripts/smoke.sh','utf8')
assert.match(smokeScript,/cp "\$TMP_DIR\/players\.json" "\$TMP_DIR\/players-live\.json"/)
assert.equal((smokeScript.match(/api\/scout-data\?section=players/g)||[]).length,0,'production smoke must not refetch the players section after the section loop')

const scoutApi=fs.readFileSync('app/api/scout-data/route.js','utf8')
const data=fs.readFileSync('lib/data.js','utf8')
assert.match(scoutApi,/full\?await getBacktestOverview\(\):await getPublicPerformanceOverview\(\)/,'public performance API must use the lightweight query path')
assert.match(data,/async function _getPublicPerformanceOverview\(\)/)
const publicPerf=data.slice(data.indexOf('async function _getPublicPerformanceOverview'),data.indexOf('async function _getBacktestOverview'))
assert.doesNotMatch(publicPerf,/scout_backtest_players|scout_preseason_player_priors|scout_preseason_team_priors/,'public performance query must not load full backtest/preseason payloads')

console.log('cloudflare deploy contract passed')
