const fs=require('node:fs')
const assert=require('node:assert/strict')

const deploy=fs.readFileSync('.github/workflows/cloudflare-deploy.yml','utf8')
const smoke=fs.readFileSync('.github/workflows/post-deploy-smoke.yml','utf8')
const health=fs.readFileSync('app/api/health/route.js','utf8')
const wrangler=fs.readFileSync('wrangler.jsonc','utf8')
const nextConfig=fs.readFileSync('next.config.mjs','utf8')
const playerDetail=fs.readFileSync('app/players/[id]/page.js','utf8')

assert.match(deploy,/Cloudflare Workers deploy/)
assert.match(deploy,/npm run deploy/)
assert.match(deploy,/GITHUB_SHA/)
assert.match(deploy,/tff-fantezi\.ecetin1998\.workers\.dev/)
assert.match(smoke,/EXPECTED_SHA/)
assert.match(smoke,/workflow_run\.head_sha/)
assert.match(health,/NEXT_PUBLIC_BUILD_SHA/)
assert.match(health,/Cache-Control':'no-store/)
assert.match(wrangler,/"name": "tff-fantezi"/)
assert.match(wrangler,/"cache":\s*\{\s*"enabled": true\s*\}/,'Cloudflare front-door cache must stay enabled.')
assert.match(nextConfig,/Cloudflare-CDN-Cache-Control/)
assert.match(nextConfig,/public, max-age=300, stale-while-revalidate=600/)
assert.match(nextConfig,/private, no-store/)
assert.match(nextConfig,/\/squad/)
assert.match(nextConfig,/\/api\/health/)
assert.doesNotMatch(playerDetail,/dynamic='force-static'/,'Tier-aware player detail cannot be globally force-static.')
assert.match(playerDetail,/getAuthState/,'Tier-aware player detail must resolve access server-side.')
const smokeScript=fs.readFileSync('scripts/smoke.sh','utf8')
assert.match(smokeScript,/cp "\$TMP_DIR\/players\.json" "\$TMP_DIR\/players-live\.json"/)
assert.equal((smokeScript.match(/api\/scout-data\?section=players/g)||[]).length,0,'production smoke must not refetch the players section after the section loop')

console.log('cloudflare deploy contract passed')
