const fs=require('node:fs')
const assert=require('node:assert/strict')

const data=fs.readFileSync('lib/data.js','utf8')
const home=fs.readFileSync('app/page.js','utf8')
const squad=fs.readFileSync('app/squad/page.js','utf8')

const section=(start,end)=>{
  const s=data.indexOf(start)
  const e=data.indexOf(end,s)
  assert.ok(s>=0&&e>s,'missing section '+start)
  return data.slice(s,e)
}

const playerLoader=section('async function _loadPlayersForRun','async function _getPlayersWithProjection')
const players=section('async function _getPlayersWithProjection','async function _getHomeOverview')
const availability=section('async function _getAvailability','async function _getRoleSignals')
const roles=section('async function _getRoleSignals','const AUTH_PLAN_TTL_MS')
const team=section('async function _getTeamDetail','async function _getBacktestOverview')
const matches=section('async function _getMatches','async function _getRecommendation')
const recommendation=section('async function _getRecommendation','async function _getAvailability')
const squadPool=section('async function _getSquadPlayerPool','function attackMatchup')

assert.match(playerLoader,/\.eq\('run_id',runId\)/)
assert.match(data,/players-for-current-run-v4/)
assert.match(players,/const run=await getCurrentRun\(\)/)
assert.match(players,/getPlayersForRunShared\(run\.id\)/)
assert.match(availability,/getPlayersForRunShared\(run\.id\)/)
assert.match(roles,/_loadProPlayersForRun\(run\.id\)/,'Role signals must come from the authorized Pro overlay.')
assert.match(team,/getPlayersForRunShared\(run\.id\)/)
assert.match(team,/getMatchesForRunShared\(run\.id\)/)
assert.match(matches,/getPlayersWithProjection\(\)/)
assert.doesNotMatch(matches,/scout_player_projections/)
assert.match(recommendation,/getPlayersForRunShared\(run\.id\)/)
assert.match(recommendation,/\.in\('recommendation_id',recIds\)/)
assert.match(recommendation,/const playerMap=new Map/)
assert.match(recommendation,/xfp:Number\(p\?\.projection\?\.xfp\?\?member\.xfp\?\?0\)/)

assert.match(data,/getHomeOverviewShared=unstable_cache\(_getHomeOverview/)
assert.match(data,/getHomeOverview=cache\(getHomeOverviewShared\)/)
assert.match(data,/getSquadPlayerPool=cache\(_getSquadPlayerPool\)/)
assert.match(squadPool,/getPlayersForRunShared\(run\.id\)/)
assert.doesNotMatch(squadPool,/v_current_player_cards/)
assert.equal((data.match(/from\('v_current_player_cards_public'\)/g)||[]).length,1,'All public current-player surfaces should share one canonical Pro-less card query.')
assert.doesNotMatch(playerLoader,/from\('v_current_player_cards'\)/,'Public player loader must not query the Pro-bearing view.')

assert.match(home,/import \{[^}]*getAuthState[^}]*getHomeOverview[^}]*\} from '@\/lib\/data'/)
assert.match(home,/getHomeOverview\(\)/)
assert.match(home,/getAuthState\(\)/)
assert.doesNotMatch(home,/getPlayersWithProjection|getMatches\(/)

assert.match(squad,/getSquadPlayerPool/)
assert.doesNotMatch(squad,/getPlayersWithProjection/)
assert.match(squad,/scout_my_squad_page/)
assert.doesNotMatch(squad,/scout_user_squad_snapshots[\s\S]*\.limit\(34\)/)

console.log('current-run alignment and hot-path contract ok')
