const fs=require('node:fs')
const assert=require('node:assert/strict')

const read=p=>fs.readFileSync(p,'utf8')
const rules=read('lib/managerCards.js')
const builder=read('components/SquadBuilder.js')
const squadPage=read('app/squad/page.js')
const squadsPage=read('app/squads/page.js')
const recommendations=read('components/ManagerCardRecommendations.js')
const picker=read('components/ManagerCardPicker.js')
const action=read('app/actions.js')
const edge=read('supabase/functions/manager-card-recommendation/index.ts')
const migration=read('supabase/migrations/20261001171523_manager_cards.sql')
const css=read('components/ManagerCards.module.css')
const layout=read('app/layout.js')
const pitch=read('components/SquadPitchView.js')
const sss=read('app/sss/page.js')

for(const id of ['triple_captain','quad_captain','bench_boost','attack','unlimited_budget']){
  assert.match(rules,new RegExp(id))
}

assert.match(rules,/ATTACK_SQUAD_LIMITS=Object\.freeze\(\{GK:2,DEF:3,MID:5,FWD:5\}\)/)
assert.match(rules,/id:'attack'[\s\S]*?budget:null/)
assert.doesNotMatch(rules,/ATTACK_FORMATION/)
assert.doesNotMatch(rules,/budget:105/)
assert.doesNotMatch(rules,/2-5-3/)

assert.match(builder,/GELİŞMİŞ • MENAJER KARTI/)
assert.match(builder,/name="manager_card"/)
assert.match(builder,/captainMultiplierForCard/)
assert.match(builder,/cardInfo\.benchBoost\?selectedTotal:xiTotal/)
assert.match(builder,/effectiveBudget/)
assert.match(builder,/effectiveSquadLimits/)
assert.match(builder,/ManagerCardPicker/)
assert.ok((builder.match(/<ManagerCardPicker/g)||[]).length>=2,'Menajer kartı seçimi hem kadro oluştur hem ilk 11 aşamasında görünmeli.')
assert.match(builder,/manager-card-roster-control/)
assert.match(builder,/Math\.max\(effectiveSquadLimits\[position\],rosterByPos\[position\]\?\.length\|\|0\)/)
assert.match(builder,/managerCardPreviewXfp/)
assert.match(builder,/2 KL/)
assert.match(builder,/3 DEF/)
assert.match(builder,/5 OS/)
assert.match(builder,/5 FOR/)
assert.doesNotMatch(builder,/105m Hücum/)
assert.doesNotMatch(builder,/ATTACK_FORMATION/)
assert.doesNotMatch(builder,/fitRosterToLimits/)

assert.match(squadPage,/initialManagerCard/)
assert.match(squadPage,/cardInfo\.benchBoost/)
assert.match(squadPage,/captainMultiplierForCard/)
assert.doesNotMatch(squadPage,/ATTACK_FORMATION/)

assert.match(squadsPage,/ManagerCardRecommendations/)
assert.match(recommendations,/manager-card-recommendation/)
assert.match(recommendations,/Kart etkisini xFP ile karşılaştır/)
assert.match(recommendations,/ManagerCardPicker/)
assert.doesNotMatch(recommendations,/105m/)
assert.match(picker,/manager-card-choice/)
assert.match(picker,/<button/)
assert.doesNotMatch(picker,/<select/)
assert.match(picker,/xFP/)

assert.match(action,/Menajer kartları Gelişmiş üyeliğe özeldir/)
assert.match(action,/manager_card:managerCard/)
assert.doesNotMatch(action,/ATTACK_FORMATION/)

assert.match(edge,/scout_subscriptions/)
assert.match(edge,/activePro/)
assert.match(edge,/benchBoost/)
assert.match(edge,/squad:card\.attack\?\{GK:2,DEF:3,MID:5,FWD:5\}/)
assert.match(edge,/effectiveBudget:card\.unlimited\?null:baseBudget/)
assert.doesNotMatch(edge,/2-5-3/)
assert.doesNotMatch(edge,/baseBudget\+5/)
assert.match(edge,/budget_limit/)
assert.match(edge,/unlimited_budget/)

assert.match(migration,/PRO_REQUIRED/)
assert.match(migration,/v_manager_card='attack'/)
assert.match(migration,/v_required_gk:=2/)
assert.match(migration,/v_required_def:=3/)
assert.match(migration,/v_required_mid:=5/)
assert.match(migration,/v_required_fwd:=5/)
assert.doesNotMatch(migration,/2-5-3/)
assert.doesNotMatch(migration,/v_base_budget_limit\+5/)
assert.match(migration,/scout_user_squad_snapshots/)

assert.match(css,/manager-card-panel/)
assert.match(css,/manager-card-buttons/)
assert.match(css,/manager-card-choice/)
assert.match(css,/manager-card-roster-control/)
assert.match(layout,/ManagerCards\.module\.css/)
assert.match(pitch,/budgetLimit=100/)
assert.match(pitch,/Bütçe sınırı yok/)
assert.match(sss,/2 KL \/ 3 DEF \/ 5 OS \/ 5 FOR/)
assert.match(sss,/100m bütçe kuralları değişmez/)
assert.doesNotMatch(sss,/105m haftalık bütçe/)

console.log('manager cards contract ok')
