const fs=require('node:fs')
const assert=require('node:assert/strict')

const data=fs.readFileSync('lib/data.js','utf8')
const page=fs.readFileSync('app/matches/page.js','utf8')
const css=fs.readFileSync('components/DataViews.module.css','utf8')

assert.ok(data.includes('total_xfp:rows.reduce((sum,p)=>sum+Number(p.xfp||0),0),'),'Team xFP must sum player xFP without double-weighting XI probability.')
assert.match(data,/top_player:ranked\[0\]\|\|null/)
assert.match(data,/name:displayName\(p\)/,'Match fantasy leaders must use the off-pitch full-name helper.')
assert.match(page,/match-team-xfp-strip/)
assert.match(page,/homeFantasy\.total_xfp/)
assert.match(page,/awayFantasy\.total_xfp/)
assert.match(page,/homeFantasy\.top_player/)
assert.match(page,/awayFantasy\.top_player/)
assert.match(page,/En yüksek xFP/)
assert.doesNotMatch(page,/short_label/,'Match cards must not render short player labels.')

assert.match(page,/match-team-shirt/)
assert.match(page,/>Ev sahibi<\/span>/)
assert.match(page,/>Deplasman<\/span>/)
assert.match(page,/<strong>Ev sahibi<\/strong>/)
assert.match(page,/<strong>Beraberlik<\/strong>/)
assert.match(page,/<strong>Deplasman<\/strong>/)
assert.match(css,/Match cards • club shirts \+ prominent probability bar 2026-09-29/)
assert.match(css,/\.scope :global\(\.match-team-shirt\)\{/)
assert.match(css,/repeating-linear-gradient\([\s\S]*?var\(--club1[\s\S]*?var\(--club2/)
assert.match(css,/\.scope :global\(\.outcome-bar-labeled\)\{[\s\S]*?height:60px;/)
assert.match(css,/Match cards • final readability authority 2026-09-29/)
assert.match(css,/height:72px !important/,'Desktop probability bar must remain materially taller than the old 28–60px variants.')
assert.match(css,/flex-direction:column/,'Probability labels must stack to avoid segment overflow.')
assert.match(css,/white-space:normal;[\s\S]*?overflow-wrap:anywhere/,'xG\/CS labels must wrap instead of ellipsizing.')
assert.match(css,/matchup-pill\):global\(\.good\)[\s\S]*?color:#176b52/,'Advantage text must keep readable contrast.')
assert.match(css,/matchup-pill\):global\(\.tough\)[\s\S]*?color:#a93e4c/,'Disadvantage text must keep readable contrast.')
assert.match(css,/Match cards • semantic matchup colors 2026-09-29/)
assert.match(css,/background:#e7f7ef !important/,'Advantage pill must stay light green.')
assert.match(css,/background:#f7e8ec !important/,'Disadvantage pill must stay red-toned.')
assert.match(css,/background:#eef1f5 !important/,'Neutral pill must stay grey.')
assert.match(css,/\.scope :global\(\.match-analysis-card\)\{[\s\S]*?min-height:730px;/)
assert.match(css,/\.scope :global\(\.match-analysis-card\):has\(:global\(\.match-technical-details\)\[open\]\)/)
assert.match(css,/\.scope :global\(\.match-team-xfp-strip\)/)
assert.doesNotMatch(css,/-webkit-line-clamp:5/,'Fantasy reading must not be clipped.')
assert.match(css,/match-team-xfp-side\)>a b\{[\s\S]*?white-space:normal;[\s\S]*?overflow-wrap:anywhere;/,'Top-player full names must wrap instead of clipping.')

console.log('match card team xFP contract ok')
