const assert=require('node:assert/strict')
const fs=require('node:fs')

const pkg=JSON.parse(fs.readFileSync('package.json','utf8'))
assert.equal(pkg.dependencies?.['@sentry/nextjs'],undefined)
assert.match(pkg.devDependencies?.['@sentry/cloudflare']||'',/^\^?11\./)
const src=fs.readFileSync('lib/observability.js','utf8')
assert.match(src,/SENTRY_DSN/)
assert.match(src,/captureException/)
assert.match(src,/console\.error/)
console.log('observability contract passed')
