const fs=require('node:fs')
const assert=require('node:assert/strict')

const read=file=>fs.readFileSync(file,'utf8')
const data=read('lib/data.js')
const availability=read('lib/availability.js')
const loginPage=read('app/login/page.js')
const loginForm=read('components/LoginForm.js')
const squadPage=read('app/squad/page.js')
const playersPage=read('app/players/page.js')
const playersTable=read('components/PlayersTable.js')
const weeklyPointsTable=read('components/WeeklyPointsTable.js')
const teamDetailPage=read('app/teams/[id]/page.js')
const playerDetail=read('app/players/[id]/page.js')
const availabilityTable=read('components/AvailabilityTable.js')
const builder=read('components/SquadBuilder.js')
const migration=read('supabase/migrations/20260928193000_deadline_and_squad_page_perf.sql')
const navAccount=read('components/NavAccountControls.js')
const appNav=read('components/AppNavLinks.js')
const playerDetailLayout=read('app/players/[id]/layout.js')
const teamDetailLayout=read('app/teams/[id]/layout.js')
const analysisCss=read('components/AnalysisViews.module.css')
const dataViewsCss=read('components/DataViews.module.css')
const squadWorkspaceCss=read('components/SquadWorkspace.module.css')
const squadLegacyCss=read('components/SquadBuilderLegacy.module.css')

assert.match(data,/const PLAYER_LIST_COLUMNS=/)
assert.match(data,/select\(PLAYER_LIST_COLUMNS\)/,'Player analysis must avoid selecting the entire public player card view.')
assert.doesNotMatch(data,/v_current_player_cards'\)\.select\('\*'\)[\s\S]{0,300}_loadPlayersForRun/)
assert.match(data,/players-for-current-run-v3/)
assert.match(data,/revalidate:300/)
assert.match(data,/current-run-v2/)
assert.match(data,/revalidate:20/)
assert.match(playersPage,/searchParams/,'Player analysis must support server-side URL filters and pagination.')
assert.match(playersPage,/getPlayersPage/)
assert.match(playersPage,/revalidate=300/)
assert.doesNotMatch(playersTable,/urlReady/)
assert.match(playersTable,/router\.replace/)
assert.match(data,/async function _getPlayersPage/)
assert.match(data,/player-detail-v2/)
assert.doesNotMatch(playerDetail,/dynamic='force-static'/,'Player detail must be request-aware so Pro fields can be gated per session.')
assert.match(playerDetail,/getAuthState/,'Player detail must resolve the current access tier server-side.')
assert.match(playerDetail,/generateStaticParams\(\)\{ return \[\] \}/)
assert.doesNotMatch(playerDetail,/Son kontrol:/)
assert.doesNotMatch(availabilityTable,/>Kontrol</)
assert.doesNotMatch(availabilityTable,/>Başlangıç</)

assert.match(loginPage,/dynamic='force-static'/)
assert.match(loginPage,/Suspense/)
assert.match(loginForm,/useSearchParams/)
assert.doesNotMatch(loginPage,/await searchParams/)

assert.match(navAccount,/auth\.getSession\(\)/)
assert.match(appNav,/auth\.getSession\(\)/)
assert.doesNotMatch(navAccount,/auth\.getUser\(\)/)
assert.doesNotMatch(appNav,/auth\.getUser\(\)/)

assert.match(squadPage,/Promise\.all\(\[\s*getAuthState\(\),[\s\S]*getSquadPlayerPool\(\),[\s\S]*getRecommendation\('recommended'\)/,'Squad public data and auth should load in parallel.')
assert.match(squadPage,/scout_my_squad_page/)
assert.doesNotMatch(squadPage,/scout_user_squad_members'\)\.select/)
assert.match(migration,/create or replace function public\.scout_my_squad_page/)
assert.match(migration,/min\(kickoff_at\)-interval '1 hour'/)
assert.match(migration,/scout_match_history_deadline_sync/)
assert.match(migration,/where public\.scout_gameweeks\.locked_at is null/)

assert.match(builder,/İlk maçtan 1 saat önce/)
assert.match(builder,/recommendedRosterMatch/)
assert.match(builder,/Model kadrosuyla birebir eşleşiyorsun/)
assert.match(builder,/modelMove/)
assert.match(builder,/clubCounts\[p\.team_id\].*MAX_PLAYERS_PER_CLUB/,'Player picker add guard must enforce the per-club limit.')
assert.match(builder,/const teamFull=MAX_PLAYERS_PER_CLUB/,'Player picker UI must disable additions from a club already at the limit.')
assert.doesNotMatch(builder,/className="roster-stage-foot"/,'Redundant helper copy under the roster pitch should stay removed.')
assert.doesNotMatch(builder,/for\(const inn of deferredPlayers\)/,'My Squad advice must not run a separate whole-pool optimizer that can contradict the canonical recommendation.')
assert.match(squadPage,/finalRows\.some\(row=>!row\)/,'Snapshot score must wait for final rows for all saved squad members.')
assert.match(squadPage,/filter\(s=>Number\(s\.gameweek\)<currentGameweek\|\|Boolean\(s\.locked_at\)\)/)
assert.match(squadPage,/squad-history-list/)
assert.match(builder,/formatDeadline/)
assert.match(availability,/split\(\/\\s\*\(\?:\\\||•\)\\s\*Rechecked\\b\/i\)/)
assert.doesNotMatch(availability,/return \[reason,'Rechecked/)

assert.equal(fs.existsSync('app/players/loading.js'),true)
assert.equal(fs.existsSync('app/squad/loading.js'),true)

/* visual-system regression guards */
assert.match(playerDetailLayout,/AnalysisViews\.module\.css/,'Player detail must load its route-scoped analysis styles.')
assert.match(teamDetailLayout,/AnalysisViews\.module\.css/,'Team detail must load its route-scoped analysis styles.')
assert.match(teamDetailLayout,/SquadBuilderLegacy\.module\.css/,'Team detail must load its base layout styles.')
assert.match(analysisCss,/Player detail • final visual authority 2026-09-29/)
assert.match(analysisCss,/player-advanced-details[\s\S]*pointer-events:auto/,'Advanced player details summary must remain clickable.')
assert.match(dataViewsCss,/Site-wide premium readability authority 2026-09-29/)
assert.match(dataViewsCss,/desktop-nav[\s\S]*overflow:visible/,'Desktop detailed-analysis menu must not be clipped by the nav scroller.')
assert.match(dataViewsCss,/outcome-bar-labeled[\s\S]*height:48px/,'Match probability bar should remain clearly readable on desktop.')
assert.match(squadWorkspaceCss,/canonical six-column player pool 2026-09-29/)
assert.match(squadWorkspaceCss,/grid-template-columns:46px minmax\(0,1fr\) 64px 64px 64px 40px/,'My Squad pool must align shirt, player, price, xFP, points, and action.')
assert.match(squadWorkspaceCss,/picker-value\):global\(\.points\)\{grid-column:5/,'Points column must not shift the action button.')
assert.match(squadLegacyCss,/restore desktop comparison 2026-09-29/)
assert.match(squadLegacyCss,/grid-template-columns:repeat\(2,minmax\(0,1fr\)\)/,'Desktop squad recommendations must stay side by side.')
assert.match(weeklyPointsTable,/weekly-position-col/,'Weekly points desktop table must show player positions.')
assert.match(weeklyPointsTable,/posLabel\(p\.position\)/,'Weekly points position labels must use Turkish position labels.')
assert.match(teamDetailPage,/rakibi/,'Single current opponent label must use correct Turkish wording.')
assert.doesNotMatch(teamDetailPage,/rakip\{currentMatches/)
assert.match(analysisCss,/Team detail • final polish authority 2026-09-29/)
assert.match(analysisCss,/Mobile player hero \+ full probability labels 2026-09-29/)
assert.match(analysisCss,/player-detail-hero\)\{[\s\S]*?min-height:0 !important/,'Mobile player hero must not retain dead vertical space.')
assert.match(analysisCss,/player-hero-score\)\{[\s\S]*?min-height:88px/,'Mobile xFP score must render as a compact highlighted card.')
assert.match(analysisCss,/team-roster-player-v3[\s\S]*grid-template-columns:minmax\(260px,1fr\) 257px !important/,'Team roster identity must not collapse under legacy grid styles.')
assert.match(analysisCss,/Team tactical mobile cards polish 2026-09-30/)
assert.match(analysisCss,/Team tactical mobile card polish 2026-09-30/)
assert.match(dataViewsCss,/Weekly mobile card polish 2026-09-30/)
assert.match(dataViewsCss,/Weekly mobile cards final polish 2026-09-30/)
assert.match(dataViewsCss,/weekly-form-meta[\s\S]*grid-template-columns:repeat\(2,minmax\(0,1fr\)\) !important/,'Mobile Fantasy Points stats should stay in a clean 2x2 grid.')

console.log('performance/deadline/readability contract passed')
