const fs=require('node:fs'),assert=require('node:assert/strict')
const source=fs.readFileSync('proxy.js','utf8')
assert.match(source,/updateSession/)
assert.match(source,/api\\/scout-data/)
assert.match(source,/api\\/player-search/)
assert.match(source,/robots\\.txt/)
assert.match(source,/sitemap\\.xml/)
console.log('proxyMatcher: SSR refresh restored with narrow exclusions')
