const fs=require('node:fs')
const assert=require('node:assert/strict')
assert.equal(fs.existsSync('proxy.js'),false,'Global proxy stays removed: auth is enforced by server routes/actions and this avoids OpenNext Node middleware bundling.')
assert.equal(fs.existsSync('middleware.js'),false,'Legacy middleware must not return.')
console.log('proxyMatcher: global proxy removed')
