const fs=require('node:fs')
const path=require('node:path')
const cp=require('node:child_process')
const assert=require('node:assert/strict')
const root=path.resolve(__dirname,'..')
const rules=JSON.parse(fs.readFileSync(path.join(root,'rules/tff-fantasy.json'),'utf8'))
const py=JSON.parse(cp.execFileSync('python3',['-c',"import json; from model.optimizer_rules import RULES; print(json.dumps(RULES,sort_keys=True))"],{cwd:root,encoding:'utf8'}))
assert.deepEqual(py,rules)
assert.match(fs.readFileSync(path.join(root,'lib/rules.js'),'utf8'),/tff-fantasy\.json/)
const sql=fs.readFileSync(path.join(root,'supabase/migrations/20260927101030_game_rules_source.sql'),'utf8')
const marker=sql.match(/values \('2026-27','([^']+)'::jsonb\)/)
assert.ok(marker,'SQL rules seed not found')
assert.deepEqual(JSON.parse(marker[1]),rules)
assert.match(fs.readFileSync(path.join(root,'model/simulateScout.js'),'utf8'),/require\('\.\.\/rules\/tff-fantasy\.json'\)/)
console.log('rulesParity: JS, Python and SQL use the same rules JSON')
