const fs=require('node:fs')
const assert=require('node:assert/strict')

const route=fs.readFileSync('app/api/scout-data/route.js','utf8')
const feed=fs.readFileSync('lib/scoutFeed.js','utf8')
const smoke=fs.readFileSync('scripts/smoke.sh','utf8')
const readme=fs.readFileSync('README.md','utf8')

assert.match(feed,/SCOUT_FEED_SECTIONS=.*summary/)
assert.match(route,/sections:SCOUT_FEED_SECTIONS/)
assert.match(route,/schema_version:SCOUT_FEED_SCHEMA_VERSION/)
assert.match(smoke,/detail_source_/)
assert.match(smoke,/players\/99999/)
assert.match(smoke,/streamed semantic 404/)
assert.match(smoke,/Sayfa bulunamadı/)
assert.match(smoke,/noindex/)
assert.doesNotMatch(smoke,/x-vercel-cache/i)
assert.match(smoke,/s-maxage=300/)
assert.match(smoke,/summary_size/)
assert.match(smoke,/curl_retry\(\)/)
assert.match(smoke,/--retry 4/)
assert.match(smoke,/--retry-all-errors/)
assert.match(readme,/20260927101100_post_deploy_restrict_sensitive_public_columns\.sql/)
assert.match(readme,/20260927101200_post_deploy_squad_write_lockdown\.sql/)

console.log('smokeContract: Cloudflare deployment smoke contract is versioned and sanitized')
