const fs=require('node:fs')
const assert=require('node:assert/strict')

const data=fs.readFileSync('lib/data.js','utf8')
const page=fs.readFileSync('app/teams/page.js','utf8')
const explorer=fs.readFileSync('components/TeamsExplorer.js','utf8')
const css=fs.readFileSync('components/DataViews.module.css','utf8')
const nav=fs.readFileSync('components/Nav.js','utf8')

assert.match(data,/async function _getTeamFixturesOverview/)
assert.match(data,/scout_team_season_stats/)
assert.match(data,/scout_team_tactical_profiles/)
assert.match(data,/v_current_player_cards/)
assert.match(data,/total_xfp:Number\(xfpMap\.get\(id\)\|\|0\)/)
assert.match(data,/fixturesByTeam/)
assert.match(data,/season_xg_per_match/)
assert.match(data,/season_xga_per_match/)
assert.match(data,/opp_xg:oppXg/)
assert.match(data,/possession:/)

assert.match(page,/TeamsExplorer/)
assert.match(page,/MH\{run\?\.gameweek\|\|'—'\} Takım Analizi/)
assert.match(page,/Haftanın rakibi, maç modeli ve sezon takım profili tek ekranda/)

assert.match(explorer,/Takım veya rakip ara/)
assert.match(explorer,/Tüm saha durumları/)
assert.match(explorer,/Tüm hücum eşleşmeleri/)
assert.match(explorer,/Bu hafta xG/)
assert.match(explorer,/Bu hafta rakip xG/)
assert.match(explorer,/metricClass\('opp_xg'\)/)
assert.match(explorer,/head\('opp_xg','Rakip xG'\)/)
assert.doesNotMatch(explorer,/\['xg_diff','Sezon xG farkı'\]/)
assert.doesNotMatch(explorer,/\['possession','Topa sahip olma'\]/)
assert.match(explorer,/Takım toplam xFP/)
assert.match(explorer,/Sezon xG \/ maç/)
assert.match(explorer,/team-analysis-mobile-card/)
assert.match(explorer,/desktop-team-analysis-table/)
assert.match(explorer,/MH\{gameweek\|\|'—'\} rakibi/)
assert.match(explorer,/venueLabel/)
assert.match(explorer,/active-team-filters/)
assert.match(explorer,/active-filter-chip/)
assert.match(explorer,/team-analysis-sort-head is-selected/)
assert.match(explorer,/is-selected-column/)
assert.match(explorer,/is-selected-fixture/)
assert.match(explorer,/team-analysis-mobile-metric/)

assert.match(css,/Team analysis explorer 2026-09-29/)
assert.match(css,/team-analysis-filters/)
assert.match(css,/team-analysis-mobile-metrics/)
assert.match(css,/desktop-team-analysis-table/)
assert.match(css,/team-mini-shirt/)
assert.match(css,/Team analysis active selection 2026-09-30/)
assert.match(css,/active-team-filters/)
assert.match(css,/is-selected-column/)
assert.match(css,/is-selected-fixture/)
assert.match(nav,/\['\/teams','Takım Analizi'\]/)

console.log('team analysis explorer contract ok')
