const fs=require('node:fs')
const assert=require('node:assert/strict')

const read=file=>fs.readFileSync(file,'utf8')

const workflow=read('.github/workflows/weekly-model-lifecycle.yml')
assert.match(workflow,/cron: '17 \* \* \* \*'/,'Weekly lifecycle must poll hourly and decide from closure state, not a fixed MH date.')
assert.match(workflow,/workflow_dispatch:/)
assert.doesNotMatch(workflow,/gh workflow run weekly-model-lifecycle\.yml/,'Scheduled event should execute the protected lifecycle directly.')
assert.match(workflow,/id-token: write/)
assert.match(workflow,/action":"status"/)
assert.match(workflow,/ready_to_advance/)
assert.match(workflow,/action":"close_backtest"/)
assert.match(workflow,/action:"prepare"/)
assert.match(workflow,/action:"prepare_current"/,'Current MH must be refreshable before kickoff when source data advances.')
assert.match(workflow,/code_sha:\$sha/,'Lifecycle must stamp the source commit SHA into generated runs.')
assert.match(workflow,/seq 0 24/,'Weekly simulation must run 25 x 2K chunks.')
assert.match(workflow,/draws=2000/)
assert.match(workflow,/mode=finalize/)
assert.match(workflow,/mode=recommended&run=\$RUN_ID/)
assert.match(workflow,/mode=alternative&run=\$RUN_ID/)
assert.match(workflow,/stage:"qa"/)
assert.match(workflow,/stage:"integrity"/)
assert.match(workflow,/stage:"bugfix"/)
assert.match(workflow,/stage:"replay"/)
assert.match(workflow,/stage:"model_gate"/)
assert.match(workflow,/action:"snapshot"/)
assert.match(workflow,/stage:"promote"/)
assert.ok(workflow.indexOf('stage:"model_gate"')<workflow.indexOf('action:"snapshot"'),'Validated model gate must run before the live snapshot.')
assert.ok(workflow.indexOf('stage:"model_gate"')<workflow.indexOf('stage:"promote"'),'Validated model gate must run before promotion.')
assert.match(workflow,/action:"verify"/)
assert.doesNotMatch(workflow,/MH7|gw=7|GAMEWEEK=7/,'Lifecycle workflow must not be tied to MH7.')

const worker=read('supabase/functions/weekly-model-lifecycle/index.ts')
assert.match(worker,/target=gw\+1/,'Target gameweek must derive from the current gameweek.')
assert.match(worker,/match_status==="Bitti"/)
assert.match(worker,/fantasy_closure==="KAPANDI"/)
assert.match(worker,/final_actual_matches/)
assert.match(worker,/SOURCE_NOT_READY/,'Candidate creation must fail closed until closure and target fixtures are complete.')
assert.match(worker,/weekly-auto:/,'Candidate generation must use an idempotency key.')
assert.match(worker,/sourceRevision\(status\.latest_source_at\)/,'Idempotency must include the latest source revision.')
assert.match(worker,/availability\.data/,'Availability freshness must contribute to the source revision.')
assert.match(worker,/current\.model_version/,'Weekly runs must inherit the validated current model engine.')
assert.match(worker,/async function linkLifecycle\(/,'Prepared candidates must persist their parent/source linkage.')
assert.match(worker,/candidate_run_id:runId/)
assert.match(worker,/source_run_id:current\.id/)
assert.match(worker,/scout_weekly_lifecycle/)
assert.doesNotMatch(worker,/ScoutPlus Weekly Auto v1/,'Weekly rollover must not silently introduce a new model engine.')
assert.match(worker,/scout_replay_player_inputs/)
assert.match(worker,/scout_replay_match_inputs/)
assert.match(worker,/scout_match_predictions/)
assert.match(worker,/scout_player_projections/)
assert.match(worker,/scout_role_signals/)
assert.match(worker,/scout_availability/)
assert.match(worker,/action==="close_backtest"/)
assert.match(worker,/action==="snapshot"/)
assert.match(worker,/action==="verify"/)
assert.match(worker,/prepareCurrentRefresh/,'Lifecycle worker must support same-gameweek pre-kickoff refresh.')
assert.match(worker,/AVAILABILITY_STALE/,'Current-week refresh must fail before simulation when availability is stale.')
assert.match(worker,/availabilityAge>24/)
assert.match(worker,/source_cutoff/)
assert.match(worker,/input_snapshot_hash/)
assert.match(worker,/code_sha/)
assert.match(worker,/config_version/)
assert.match(worker,/codeRevision/,'Intraday candidates must be keyed by code revision to avoid stale candidate reuse.')
assert.match(worker,/shareTotals/,'Intraday availability changes must renormalize team goal and assist shares.')
assert.doesNotMatch(worker,/gameweek\s*=\s*7|GAMEWEEK\s*=\s*7/)

const sim=read('supabase/functions/run-live-sim-chunk/index.ts')
assert.match(sim,/searchParams\.get\("gw"\)/)
assert.match(sim,/searchParams\.get\("run"\)/)
assert.match(sim,/searchParams\.get\("benchmark"\)/)
assert.match(sim,/mins\[i\]>60\?SCORING\.appearance_60:0/,'Official appearance rule is strictly >60 minutes.')
assert.match(sim,/mins\[i\]>=60&&score/,'Official clean-sheet minimum remains >=60 minutes.')
assert.match(sim,/scout_finalize_simulation_run/)
assert.match(sim,/scout_goal_distribution_config/)
assert.match(sim,/teamGoals\(match\.home_lambda\)/,'Live MC must use the gated goal-distribution sampler.')
assert.match(sim,/populate_match_predictions_nb/,'Finalized match cards must use the same gated NB2 distribution.')
assert.match(sim,/scout_game_rules/)
assert.doesNotMatch(sim,/const SCORING=\{/,'Weekly simulator must read scoring from canonical rules.')
assert.match(sim,/minDraws<50000/)
assert.doesNotMatch(sim,/live-mh7|GAMEWEEK=7|expected 449/)

const control=read('supabase/functions/model-refresh-control/index.ts')
assert.match(control,/upstream_configured/)
assert.match(control,/body\.strict!==false/)
assert.match(control,/stage==="bugfix"/)
assert.match(control,/stage==="model_gate"/)
assert.match(control,/engineSignature/)
assert.match(control,/sameEngine&&Boolean\(parentGate\.data\.backtest_pass\)&&\(sameConfig\|\|gatedGoalDistChange\)/,'Promotion requires an unchanged engine and either unchanged config or an approved component gate.')
assert.match(control,/gate_passed/)
assert.match(control,/gatedGoalDistChange/)
assert.match(control,/goalConfigFingerprint/,'Goal-distribution gate must validate the full active config fingerprint.')
assert.doesNotMatch(control,/stage==="current_context"/,'Current-week refresh must remain candidate-based and atomic.')
assert.doesNotMatch(sim,/scout_finalize_current_simulation_run/,'Current-week refresh must not mutate the published run in place.')
assert.match(control,/\.\.\.\(patch\.details\|\|\{\}\)/,'Release gate details must accumulate instead of replacing earlier QA evidence.')

const migration=read('supabase/migrations/20260928181000_weekly_lifecycle_runtime.sql')
assert.match(migration,/scout_finalize_simulation_run/)
assert.match(migration,/scout_snapshot_live_backtest/)
assert.match(migration,/scout_close_live_backtest/)
assert.match(migration,/90\*coalesce\(fc\.fixture_count,0\)/,'Run QA must allow DGW minutes.')
assert.match(migration,/minute_sum-990\*fixture_count/,'Team-minute invariant must scale for DGWs.')
assert.match(migration,/match_count>=18 and mod\(match_count,2\)=0/,'Run QA must accept valid DGW fixture counts.')
assert.match(migration,/refresh_top25_gb_v1/)
assert.match(migration,/refresh_top25_v23/)

console.log('weekly lifecycle contract passed')
