import {defineConfig,globalIgnores} from 'eslint/config'

export default defineConfig([
  {
    files:['**/*.{js,mjs,cjs,jsx}'],
    languageOptions:{
      ecmaVersion:'latest',
      sourceType:'module',
      globals:{
        console:'readonly',
        process:'readonly',
        Buffer:'readonly',
        URL:'readonly',
        fetch:'readonly',
        crypto:'readonly',
        setTimeout:'readonly',
        clearTimeout:'readonly',
        structuredClone:'readonly',
        TextEncoder:'readonly',
        window:'readonly',
        document:'readonly',
        navigator:'readonly',
        localStorage:'readonly',
        history:'readonly',
        location:'readonly',
        scrollTo:'readonly',
      }
    },
    rules:{
      'no-undef':'error',
      'no-unreachable':'error',
      'no-dupe-keys':'error',
      'no-dupe-args':'error',
      'no-constant-condition':['error',{checkLoops:false}],
      'no-control-regex':'error',
      'no-func-assign':'error',
      'no-import-assign':'error',
      'no-self-assign':'error',
      'no-sparse-arrays':'error',
      'no-unexpected-multiline':'error',
      'valid-typeof':'error',
    }
  },
  {
    files:['supabase/functions/**/*.{ts,js}'],
    rules:{'no-undef':'off'}
  },
  globalIgnores(['.next/**','out/**','node_modules/**'])
])
