import Link from 'next/link'
import { getMatches, getPlayersWithProjection, getRecommendation } from '@/lib/data'
export const revalidate=300
export default async function Home(){
  const [{players,run},{matches},{recommendation,members}]=await Promise.all([getPlayersWithProjection(),getMatches(),getRecommendation('recommended')])
  const sorted=[...players].sort((a,b)=>Number(b.projection.xfp)-Number(a.projection.xfp)), best=sorted[0]
  const value=[...players].sort((a,b)=>Number(b.projection.value_score)-Number(a.projection.value_score))[0]
  const minutes=[...players].sort((a,b)=>Number(b.projection.x_minutes)-Number(a.projection.x_minutes))[0]
  const six=[...players].sort((a,b)=>Number(b.projection.six_plus_probability)-Number(a.projection.six_plus_probability))[0]
  const featured=[...matches].sort((a,b)=>Math.max(Number(b.home_win_probability),Number(b.away_win_probability))-Math.max(Number(a.home_win_probability),Number(a.away_win_probability)))[0]
  const xi=members.filter(m=>m.squad_slot==='XI')
  return <>
    <section className="hero"><div><div className="eyebrow">GW{run?.gameweek||'—'} • {(run?.simulation_count||0).toLocaleString('tr-TR')} simülasyon</div><h1>Fantasy takımını tahminle değil,<br/><span>veriyle yönet.</span></h1><p>xFP, rol, dakika, fikstür ve olasılık modelini tek ekranda birleştir.</p><div className="hero-actions"><Link href="/players" className="cta">Oyuncuları incele</Link><Link href="/squad" className="secondary">Takımımı analiz et</Link></div></div><div className="hero-score"><span>Önerilen XI</span><strong>{Number(recommendation?.captain_xfp||0).toFixed(2)}</strong><small>kaptanlı xFP</small></div></section>
    <div className="grid stats"><div className="card stat"><span>Model lideri</span><strong>{best?.full_name||'—'}</strong><em>{Number(best?.projection?.xfp||0).toFixed(2)} xFP</em></div><div className="card stat"><span>En iyi F/P</span><strong>{value?.full_name||'—'}</strong><em>{Number(value?.projection?.value_score||0).toFixed(2)} xFP/m</em></div><div className="card stat"><span>En güvenli dakika</span><strong>{minutes?.full_name||'—'}</strong><em>{Number(minutes?.projection?.x_minutes||0).toFixed(1)} xDakika</em></div><div className="card stat"><span>6+ puan</span><strong>{six?.full_name||'—'}</strong><em>{(Number(six?.projection?.six_plus_probability||0)*100).toFixed(1)}%</em></div></div>
    <div className="split"><section className="card panel"><div className="panel-head"><div><span className="eyebrow">ÖNERİLEN KADRO</span><h2>GW{run?.gameweek||'—'} İlk 11</h2></div><span className="pill">{Number(recommendation?.budget||0).toFixed(1)}m</span></div><div className="squad-list">{xi.map(m=><div key={m.player_id} className="squad-row"><span className={`pos ${m.player?.position}`}>{m.player?.position}</span><div><b>{m.player?.full_name}</b><small>{m.team} • {Number(m.player?.price||0).toFixed(1)}m</small></div><strong>{Number(m.xfp||0).toFixed(2)}</strong>{m.is_captain?<span className="captain">C</span>:null}</div>)}</div></section>
    <section className="card panel"><div className="panel-head"><div><span className="eyebrow">HAFTANIN ÖNE ÇIKAN MAÇI</span><h2>{featured?.home_team} — {featured?.away_team}</h2></div><span className="pill good">{featured?`${(Math.max(Number(featured.home_win_probability),Number(featured.away_win_probability))*100).toFixed(1)}%`:'—'}</span></div>{featured?<><div className="match-hero"><div><strong>{Number(featured.home_xg).toFixed(2)}</strong><span>{featured.home_team} xG</span></div><div className="score-pick"><small>en olası</small><b>{featured.top_score}</b><small>{(Number(featured.top_score_probability)*100).toFixed(1)}%</small></div><div><strong>{Number(featured.away_xg).toFixed(2)}</strong><span>{featured.away_team} xG</span></div></div><div className="probbar"><i style={{width:`${Number(featured.home_win_probability)*100}%`}}/><span>1 {(Number(featured.home_win_probability)*100).toFixed(1)}%</span></div><div className="probbar"><i style={{width:`${Number(featured.draw_probability)*100}%`}}/><span>X {(Number(featured.draw_probability)*100).toFixed(1)}%</span></div><div className="probbar"><i style={{width:`${Number(featured.away_win_probability)*100}%`}}/><span>2 {(Number(featured.away_win_probability)*100).toFixed(1)}%</span></div></>:null}</section></div>
  </>
}
