'use client'
import Link from 'next/link'
import {useEffect,useRef,useState} from 'react'
export default function GlobalPlayerSearch(){
  const [open,setOpen]=useState(false),[q,setQ]=useState(''),[rows,setRows]=useState([]),[loading,setLoading]=useState(false);const inputRef=useRef(null)
  useEffect(()=>{if(!open)return;const id=requestAnimationFrame(()=>inputRef.current?.focus());const onKey=e=>{if(e.key==='Escape')setOpen(false)};window.addEventListener('keydown',onKey);return()=>{cancelAnimationFrame(id);window.removeEventListener('keydown',onKey)}},[open])
  useEffect(()=>{const needle=q.trim();if(!open||needle.length<2){setRows([]);setLoading(false);return}const c=new AbortController();const t=setTimeout(async()=>{setLoading(true);try{const res=await fetch('/api/player-search?q='+encodeURIComponent(needle),{signal:c.signal});const json=await res.json();setRows(Array.isArray(json?.players)?json.players:[])}catch(err){if(err?.name!=='AbortError')setRows([])}finally{setLoading(false)}},180);return()=>{clearTimeout(t);c.abort()}},[q,open])
  const close=()=>{setOpen(false);setQ('');setRows([])}
  return <><button type="button" className="global-player-search-trigger" onClick={()=>setOpen(true)} aria-label="Oyuncu ara" title="Oyuncu ara"><svg viewBox="0 0 24 24"><circle cx="11" cy="11" r="6.5"/><path d="m16 16 4 4"/></svg></button>{open?<div className="global-player-search-layer" role="dialog" aria-modal="true"><button type="button" className="global-search-backdrop" onClick={close} aria-label="Aramayı kapat"/><div className="global-player-search-panel"><div className="global-player-search-input"><svg viewBox="0 0 24 24"><circle cx="11" cy="11" r="6.5"/><path d="m16 16 4 4"/></svg><input ref={inputRef} value={q} onChange={e=>setQ(e.target.value)} placeholder="Oyuncu ara..."/><button type="button" onClick={close}>Kapat</button></div><div className="global-player-search-results">{q.trim().length<2?<p>En az 2 harf yaz.</p>:loading?<p>Aranıyor…</p>:rows.length?rows.map(row=><Link href={'/players/'+row.id} onClick={close} key={row.id}><span className={'pos '+row.position}>{row.position==='MID'?'OS':row.position==='FWD'?'FOR':row.position==='GK'?'KL':'DEF'}</span><span><b>{row.full_name}</b><small>{row.team} • {Number(row.price||0).toFixed(1)}m</small></span><strong>{Number(row.xfp||0).toFixed(1)}<small>xFP</small></strong></Link>):<p>Oyuncu bulunamadı.</p>}</div></div></div>:null}</>
}
